[package]
name = "goblin"
version = "0.0.0"
authors = ["m4b <m4b.github.io@gmail.com>"]
readme = "README.md"
keywords = ["binary", "elf", "mach", "pe", "cross-platform"]
repository = "https://github.com/m4b/goblin"
license = "MIT"
description = "An impish, cross-platform binary parsing and loading crate"

[lib]
crate-type = ["rlib", "dylib"]

[features]
default = []
elf32 = []
elf = []
mach = []
mach32 = []
pe = []
pe32 = []
goblin = []
