[package]
name = "goblin"
version = "0.0.7"
authors = ["m4b <m4b.github.io@gmail.com>", "seu <seu@panopticon.re>"]
readme = "README.md"
keywords = ["binary", "elf", "mach", "pe", "cross-platform"]
repository = "https://github.com/m4b/goblin"
license = "MIT"
description = "An impish, cross-platform binary parsing and loading crate"

[lib]

[dependencies.quick-error]
version = "1.1.0"

[dependencies.scroll]
version = "0.2.0"
optional = true
git = "https://github.com/m4b/scroll"

[dependencies.scroll_derive]
version = "0.1.0"
optional = true
git = "https://github.com/m4b/scroll_derive"

[features]
default = ["std", "elf32", "elf64", "mach32", "mach64", "pe32", "pe64", "goblin", "endian_fd", "archive"]
std = []
elf32 = []
elf64 = []
mach32 = []
mach64 = []
pe32 = []
pe64 = []
goblin = []
archive = ["std", "endian_fd"]
endian_fd = ["scroll", "scroll_derive"]
